deletiontests/azure/azure_delete_test.go, pkg/ctrlclient/client.go, tests/autoscaler/autoscaler_test.go, tests/cptcconnectivity/cptcconnectivity_test.go, tests/ingress/ingress_test.go
K8s client creation functions don't use the passed context variable.
Drop it.
=> Drop unused context parameter

pkg/capiutil/cluster.go, pkg/capiutil/error.go
Add new `capiutil` package to hold CAPI related helper functions such as
finding `Cluster`.
=> Add helper package for CAPI related functions

deletiontests/azure/azure_delete_test.go, pkg/azure/credentials/azurecredentials.go
Recently we used `ctrl` import alias for `controller-runtime/pkg/client`
to replace the ambiguous `client` package prefix. It feels nicer so this
change aligns the use for e2e tests.
=> Align controller-runtime imports

pkg/provider/azure.go, pkg/provider/common.go, pkg/provider/error.go, pkg/provider/spec.go
This adds initial structure for provider specific support
implementation. `provider.Support` is meant to be used for provider
specific functionality that can be used for implementing tests in
provider independent way.
Initial Azure support is also included, as extracted from upcoming
multi-AZ test.
=> Add: Provider support & initial version for Azure

run_go_test.sh
Using `tee` to collect `go test` logs has the side effect of losing the exit code. We need the exit code of `go test`, so we need the `pipefail` option in the bash script. It's only available in bash,  that's why I changed the interpreter.
=> Fail when tests fail

tests/autoscaler/autoscaler_test.go
during autoscaling test it happened that the replicas change in the deployment causes a conflict error.
This pr adds a backoff retry to avoid this from making the whole test to fail
=> retry to update the deployment to overcome conflict errors

giantswarm-plugin.yaml
We always want to run the latest version of the plugins' docker image.
=> Always pull plugins' docker image

Dockerfile, giantswarm-plugin.yaml, run_go_test.sh
We need to install:
- tool to generate `junit` report from `go test` output, because that's what `sonobuoy` understands.
- `nodejs` tool to merge together different `junit` reports, because we generate one for the `deletion` test and one for the rest.
=> Generate junit report so that sonobuoy parses the result

run_go_test.sh
`-timeout` value is duration string so it understands hours as well.
Less than 24h is also better value in case we run nightly tests at one
point.
=> Adjust tests' timeout value

pkg/capiutil/common.go, tests/autoscaler/autoscaler_test.go, tests/availabilityzones/multiaz_test.go
We use the retry mechanism in several places of our tests. When something goes wrong, the retry mechanism will wait up until the specified parameter. Let's try to choose deliberate the amount of time, instead of just defaulting to "a long time".
Do you think this is enough time?
=> Don't wait that long before failing

giantswarm-plugin.yaml, run_go_test.sh
When we are debugging the tests, it would be useful to keep the resources that got created, instead of deleting everything. We need to conditionally run the deletion cluster test.
=> Conditionally run the deletion cluster test

pkg/azure/internal/client/vmss.go, pkg/azure/spec.go, pkg/provider/azure.go
I got a panic while running the tests, I believe it's an stack overflow due to recursion.
<details>
<summary>Stack trace</summary>
```
/usr/local/go/src/runtime/panic.go:1116 +0x72
/usr/local/go/src/runtime/stack.go:1067 +0x78d
/usr/local/go/src/runtime/asm_amd64.s:449 +0x8f
/app/pkg/azure/internal/client/vmss.go:27 +0xaa fp=0xc02106a380 sp=0xc02106a378 pc=0x14e65aa
/app/pkg/azure/internal/client/vmss.go:28 +0x74 fp=0xc02106a3e0 sp=0xc02106a380 pc=0x14e6574
/app/pkg/azure/internal/client/vmss.go:28 +0x74 fp=0xc02106a440 sp=0xc02106a3e0 pc=0x14e6574
/app/pkg/azure/internal/client/vmss.go:28 +0x74 fp=0xc02106a4a0 sp=0xc02106a440 pc=0x14e6574
/app/pkg/azure/internal/client/vmss.go:28 +0x74 fp=0xc02106a500 sp=0xc02106a4a0 pc=0x14e6574
/app/pkg/azure/internal/client/vmss.go:28 +0x74 …
```
=> Change interface so it does not lead to infinite recursion

error.go, machinepool_test.go
Towards https://github.com/giantswarm/giantswarm/issues/15477
Make sure that `Spark` CR exists for every node pool. Since we don't label `Spark` CRs with the node pool name, we need to list all `Spark` CRs in the `Cluster` and then try to find the one named after the node pool.
=> Assert that Spark CR exists for node pool

autoscaler_test.go, azurecluster_test.go, azuremachinepool_test.go, machinepool_test.go, pkg/capiutil/azuremachinepool.go, pkg/capiutil/label.go, pkg/capiutil/machinepool.go, pkg/provider/azure.go
Towards https://github.com/giantswarm/giantswarm/issues/14803
~There is a test that creates a new node pool, so the assumptions that some tests made about how many resources to find are wrong depending on when they are executed. We don't want a race condition, so I want to try to make assertions only on the `Ready` node pools, because tests are only executed after the created cluster is `Ready`. We are not interested on other node pools that may be created by other tests.~
I changed the approach so instead of filtering out node pools that were not Ready, I'm labeling the cluster that's created for the multi AZ test. That way I can filter out in the rest of the tests.
=> Filter out testing node pools when asserting things

azurecluster_test.go, error.go, pkg/capiutil/azuremachinepool.go, pkg/capiutil/machinepool.go
This assertion fails every once in a while because a different test creates a new node pool so the number of subnets is not the expected one. I added a retry because eventually they should match.
=> Retry matching number of subnets to number of node pools

giantswarm-plugin.yaml, run_go_test.sh
Toward https://github.com/giantswarm/giantswarm/issues/16664
I would like to run only [`app` test](https://github.com/giantswarm/sonobuoy-plugin/blob/master/apps_test.go) here and want to make this rule more general.
=> Run tests only if they match to the regexp

autoscaler_test.go
sometimes 5 minutes for the autoscaler to kick in is not enough
=> increase timeout for the autoscaler test

autoscaler_test.go, cluster_test.go, machinepool_test.go, multiaz_test.go
We have a tekton pipeline called `azure` that runs these tests on azure. We also have another pipeline called `apps` that runs the app test inside this plugin. Instead of having this `apps` pipeline, I believe it's best to have [a new pipeline similar to the `azure` one that runs all these tests on aws clusters](https://github.com/giantswarm/test-infra/pull/148/files).
Since most of these tests are not implemented on aws just yet, this PR skips those tests, but keeps those that should work on all providers. Next time we want to test the apps, we can just run [this new pipeline](https://github.com/giantswarm/test-infra/pull/148/files) that will run the apps test together with other tests, instead of using the `apps` pipeline, that will be removed.
=> Skip now implemented tests on AWS

cluster_test.go, pkg/capiutil/common.go
The `cluster` test was not working as it was using a `Condition` that we don't have in legacy releases
=> fixed legacy cluster test

networkpolicy_test.go
Not sure if a timing issue or something else is wrong, but it doesn't harm to check for it.
```
--- FAIL: Test_NetworkPolicy (0.11s)
panic: runtime error: index out of range [0] with length 0 [recovered]
panic: runtime error: index out of range [0] with length 0
goroutine 62 [running]:
testing.tRunner.func1.2({0x1d87520, 0xc0006d8d68})
/usr/local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1212 +0x218
panic({0x1d87520, 0xc0006d8d68})
/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/giantswarm/sonobuoy-plugin/v5.Test_NetworkPolicy.func2()
/app/networkpolicy_test.go:71 +0x23d
github.com/cenkalti/backoff.RetryNotify(0xc00067bf28, {0x7f040ddc43f8, 0xc000831200}, 0xc000831230) …
```
=> Guard against pod not having ContainerStatuses yet

cgroupsv1_test.go, multiaz_test.go, pkg/provider/aws.go, pkg/provider/azure.go, pkg/provider/spec.go
Add new test to try and deploy a cgroups v1 node pool and avoid the mistake I made on release 18.0.1
=> add new test for cgroups v1 node pools

cilium_test.go, error.go, go.sum
Towards: https://github.com/giantswarm/giantswarm/issues/23554
this PR adds a new test that checks cilium app is deployed correctly and that `cilium status` returns an healthy result
=> Add new test for cilium health

autoscaler_test.go
the autoscaler test fails often because scale down does not happen.
I think it might be because nodes are pretty full and there might not be enough room for all pods to fit.
This PR changes the test to make it scale up by 2 nodes and then back down by 1.
It should minimize the problem from happening
=> scale up nodes by 2 to minimize failed downscaling
